modLoader = "javafml"
loaderVersion = "[37,)"
license = "MIT"
issueTrackerURL = "https://github.com/Jonathing/lazydfu/issues"
[[mods]]
modId = "lazydfu"
version = "0.1.3"
displayName = "LazyDFU"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge"
logoFile = "icon.png"
credits = "Initial port to Forge by Corgi Taco. Updated version maintained by Jonathing."
authors = "tuxed"
description = '''Makes the DataFixerUpper more lazy.'''
